### ISSUE TITLE
ipadapter model load node will not find models 

### ISSUE THREAD

**Issue by klinter007** [cubiq/ComfyUI_IPAdapter_plus#123]
<img width="568" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/131816305/e259b50f-c912-46d4-b69f-52f59b3d93d7">

model files are in model folder for sure. i've checked so many times.
tried re-installing no help

**Comment by cubiq** [comment]
the priority is as follow:
- anything declared in the extra_model_paths.yaml under the param name "ipadapter"
- comfyui/models/ipadapter/
- comfyui/custom_nodes/comfyui_ipadapter_plus/models

if you created a models/ipadapter folder you have to place the models there, if the directory is not present then the models should be in the local extension directory. if you specified a location in the extra_model_paths.yaml file, then that will be used

**Comment by vilanele** [comment]
Same error here, no matter in which of the three folders of previous post by cubiq I put my models, they don"t show in the "Load IPAdapter Model" node. Shutting down, re-installing ... no help. ;)

**Comment by vilanele** [comment]
Rectification, it works in the third case only, when I put my models in comfyui/custom_nodes/comfyui_ip_adapter_plus/models. It does not work with the location in extra_model_paths.yaml neither with the default comfyui/models/ipadapter. Thanks

**Comment by cubiq** [comment]
maybe you have an old version of the extension?

**Comment by cedarconnor** [comment]
Same error here. I did a full update of Comfy. I also reinstalled IPAdaptor. Older, previously working workflows no longer see the models folder.

**Comment by cubiq** [comment]
check if you have a comfyui/models/ipadapter/ directory

**Comment by LeMargoulain** [comment]
Same here, tried comfyui/models/ipadapter/ directory, the legacy one and the extra_model_paths.yaml and nothing worked even after reinstalling unfortunately.

**Comment by Jellybit** [comment]
I have the same issue, but only for the CLIP Vision model. No matter what I try, it never shows up. Like the others, I tried moving the clip_vision folder to the plugin's models folder, and the main ComfyUI/models folder. I tried putting it in the root of both too. Nothing.

**Comment by LeMargoulain** [comment]
I might have figured out something, in my case it might have something to do with OneDrive. I change the yaml file path to be at the root of my C: drive and now it is able to find my models. I hope it will help some of you!

**Comment by cubiq** [comment]
guys, you are asking for troubles in using onedrive

**Comment by LeMargoulain** [comment]
Yeah it's the worst but I didn't realize it came automatically with windows 11 at the beginning, so now my document tab is kinda cursed I guess.

**Comment by ZDOSt** [comment]
Have been having this issue since the most recent update. IPAdapter can't see the models no matter what folder they're in. Specifying location in the extra_model_paths.yaml is ignored
Installing models directly from ComfyUI places them in comfyui/models/ipadapter
But IPAdapter still can't see the models. 
Re-installing the extension didn't work either.

**Comment by cubiq** [comment]
can you try the version I've uploaded yesterday?

**Comment by ZDOSt** [comment]
The issue started after I updated this morning. Everything was working great before then.

**Comment by ZDOSt** [comment]
Going to try a few things, culminating with a full ComfyUI reinstall. It would seem that my issue is isolated, so maybe there is something in my installation that's messing with the new update. Will report back!

**Comment by konradre** [comment]
Had the same issue, but resolved by putting models in the comfyui/custom_nodes/comfyui_ip_adapter_plus/models folder.

**Comment by cubiq** [comment]
closing for lack of updates, feel free to reopen if you still have issues

**Comment by devZu9** [comment]
The problem is not solved. Reinstalled ComfyUI and ComfyUI IP Adapter plus.
I placed the models in these folders:
\ComfyUI\models\ipadapter\
\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models\
Still "Load IP Adapter Model" does not see the files.

2024-01-08

p.s. windows 10

**Comment by jameslanman** [comment]
PSA: I couldn't get this to work forever and then I realized I misspelled ipadapter in my extra_model_paths.yaml file as "ipadaptor" *facepalm*. If you are reusing files from Automatic1111, just add the path in your extra_model_paths.yaml file under 
```
checkpoints: models/Stable-diffusion
configs: models/Stable-diffusion
```
and make sure to write this verbatim:
```
ipadapter: models/ipadapter
clip_vision: models/clip_vision/
```

If there isn't already a folder under models with either of those names, create one named ipadapter and clip_vision respectively. Follow the instructions in Github and download the Clip vision models as well.

**Comment by Upasunda** [comment]
I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added:
`folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`

and that seems to have solved the issue.

**Comment by cubiq** [comment]
it's "ipadapter" all lowercase

**Comment by Sundance2318** [comment]
Sorry, my bad in spelling. But it doesn't change anything about the described problem about the node takes the model once from one folder and next time from another folder..

**Comment by cubiq** [comment]
the ipadapter folder inside ComfyUI/models/ needs to be deleted if you want to use the models inside the IPAdapter extension folder.

the upper/lower case is important in linux, so check that too.

**Comment by vivekvp1** [comment]
Hello,
I do not have a ipadapters folder in **ComfyUI_windows_portable\ComfyUI\models** but do have **ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models**  (but there are no models in there) but still get the error.  Is the set up correct, I am just lacking an model to use?  Thanks,

**Comment by Turboeskimo** [comment]
Load IPAdapter Model could not find the models when they were in Custom Nodes area. I just created new folder: ComfyUI->Models->ipadapter and placed the models in it - now they can be seen in the Load IPAdapter Model node, but now the Load IPAdapter node can't see them) Not sure why these nodes look for the models in different folders, but I guess I'll have to duplicate everything. Anyways the solution is the ipadapter folder in models folder of ComfyUI.

**Comment by nashPrat** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

thanks this worked

**Comment by Juarrow** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

Only thing that worked for me, too.

**Comment by ardiologyAI** [comment]
[FIXED] your base path should be like this:
![Capture](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/150102062/2d766b52-34a3-473b-b15e-3f7f2f3a9baf)

**Comment by 1manfactory** [comment]
Just for reference.

I had to create folder _**comfyui/models/ipadapter/**_ and place the model there.

Now at least this step works again.

Windows 11

**Comment by reglee911** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

it's working, thanks

**Comment by giusparsifal** [comment]
Hello, I've tried all solutions written here, for some of you worked, but I still not able to work it out. I've tried also yo unistall and install again but nothing seems to work.
I had a similar problem (with no result) with another workflow, can't find, in that case, ip-adapter.bin, even if I have the files.
Don't know aht to do else...
Thanks a lot everybody for suggestion though!

**Comment by aswordok** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

Thank you. That's the right solution

**Comment by jeffwheeless** [comment]
if anyone is still struggling with this change this class IPAdapterModelLoader inside of IPAdapaterPlus.py and it will give you debugging of where to put the models. My problem was the models folder needed to be named IpAdapter instead of ipadapter.

`class SetEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, set):
            return list(obj)
        return json.JSONEncoder.default(self, obj)
    
class IPAdapterModelLoader:
    @classmethod
    def INPUT_TYPES(s):
        # debug_list = json.dumps(folder_paths.folder_names_and_paths["ipadapter"])
        debug_list = json.dumps(folder_paths.folder_names_and_paths["ipadapter"], cls=SetEncoder)
        print(f"\033[33mINFO: ipadapter " + str(debug_list) + "\033[0m") #  loaded from 
        return {"required": { "ipadapter_file": (folder_paths.get_filename_list("ipadapter"), )}}

    RETURN_TYPES = ("IPADAPTER",)
    FUNCTION = "load_ipadapter_model"
    CATEGORY = "ipadapter/loaders"

    def load_ipadapter_model(self, ipadapter_file):
        ipadapter_file = folder_paths.get_full_path("ipadapter", ipadapter_file)
        return (ipadapter_model_loader(ipadapter_file),)`

**Comment by Troyificus** [comment]
I've tried every single solution above, and I'm still getting the same error:
```

Error occurred when executing IPAdapterUnifiedLoader:

IPAdapter model not found.

  File "C:\Users\Trism\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main\IPAdapterPlus.py", line 515, in load_models
    raise Exception("IPAdapter model not found.")
```

**Comment by RoaringAPE** [comment]
same

**Comment by Troyificus** [comment]
Found a solution, I've updated my post.

**Comment by Jp-west** [comment]
I attempted to resolve this issue by implementing all the suggested workarounds; however, they were unsuccessful. Subsequently, I installed all the SDXL and SD1.5 iPadapters models from the ComfyUI manager, including Loras, and this solution proved to be effective.
![IpAdapter](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/173507954/1530e8b5-a07b-4725-afe7-87a3a14756ae)

**Comment by Vektor369** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

You have **GOT** to be £µ¢א¡π9 joking me. One line?!? _One line!?!_ This error came up **_last year_**. How can this still be a thing!?! I spent all day on this!

Well, thank you very much, sir. You are my hero.

(One line...)

**Comment by Gocry** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

thanks bro, I've been suffering from it for days

**Comment by 37OMKAR** [comment]
sing xformers attention in VAE
Using xformers attention in VAE
INFO: Clip Vision model loaded from F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing!!! IPAdapter model not found.
Traceback (most recent call last):
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 535, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

i done every thing but its asking for a .py file and in models there is only saftensor and bin help

**Comment by NiceWonBruva** [comment]
Below is the answer posted by upasunda on feb11th.
For me it went like this... 
C:\Users\Mike\AppData\Roaming\StabilityMatrix\Packages\ComfyUI
In there was a file (Yes in that list there) called folder_paths.py
Open that WITH NOTEBOOK
Then add the line he mentioned " folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions) "
Click save
Then reload comfyui
It will now work.
Been on this issue for almost an hour so yeah thought I'd help any who were still confused.
Happy headaches <3

[Upasunda](https://github.com/Upasunda) commented [on Feb 11](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/123#issuecomment-1937867603)
I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added:
folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)

and that seems to have solved the issue.

**Comment by monica-dulgheru** [comment]
I installed [ComfyUI ](https://github.com/comfyanonymous/ComfyUI#manual-install-windows-linux) manually and [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) as at 2024-08-29. 

After much time unsuccessfully trying to get ComfyUI to output a more informative error message (where is it searching for the ipadapter models?) by changing change main.py and execution.py and IPAdapaterPlus.py I gave up and just traced the methods myself. 

I quickly found just like @Upasunda that the ipadapter path is still not in the folder_paths.py in the ComfyUI root directory. 

So this is the full set-up that worked for me:

Add `
folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`

to:  folder_paths.py in the ComfyUI root directory

Take all the of the IPAdapter models from https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models and put them in ComfyUI/models/ipadapter folder -> where you will have to create the ipadapter folder in the ComfyUI/models folder. 

IMPORTANT: Make sure what you write in folder_paths.py and what you name your folder in ComfyUI/models/ is THE SAME. Eg: if you use "ipadapter**s**" in ([os.path.join(models_dir, "ipadapter**s**")] then name your folder adapter**s**. If you're using singular, then use the singular.

**Comment by MrW00dy** [comment]
The SOLUTION for me was finding the "extra_model_paths.yaml" mentioned in the first comment and looking at the paths for ipadapter and don't you know it I'm using Stability Matrix and my paths are all different, put files in correct path and it works.

**Comment by azamet90** [comment]
> I installed [ComfyUI ](https://github.com/comfyanonymous/ComfyUI#manual-install-windows-linux) manually and [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) as at 2024-08-29.
> 
> After much time unsuccessfully trying to get ComfyUI to output a more informative error message (where is it searching for the ipadapter models?) by changing change main.py and execution.py and IPAdapaterPlus.py I gave up and just traced the methods myself.
> 
> I quickly found just like @Upasunda that the ipadapter path is still not in the folder_paths.py in the ComfyUI root directory.
> 
> So this is the full set-up that worked for me:
> 
> Add ` folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> to: folder_paths.py in the ComfyUI root directory
> 
> Take all the of the IPAdapter models from https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models and put them in ComfyUI/models/ipadapter folder -> where you will have to create the ipadapter folder in the ComfyUI/models folder.
> 
> IMPORTANT: Make sure what you write in folder_paths.py and what you name your folder in ComfyUI/models/ is THE SAME. Eg: if you use "ipadapter**s**" in ([os.path.join(models_dir, "ipadapter**s**")] then name your folder adapter**s**. If you're using singular, then use the singular when you create your folder.
> 
> For folder_names_and_paths["ipadapter"] you **must use** the word **ipadapter**.

this one did not fix my problem, i have the same trash problem -.-

**Comment by samsesuj** [comment]
> I attempted to resolve this issue by implementing all the suggested workarounds; however, they were unsuccessful. Subsequently, I installed all the SDXL and SD1.5 iPadapters models from the ComfyUI manager, including Loras, and this solution proved to be effective. ![IpAdapter](https://private-user-images.githubusercontent.com/173507954/341894045-1530e8b5-a07b-4725-afe7-87a3a14756ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4Nzg1MjgsIm5iZiI6MTczNDg3ODIyOCwicGF0aCI6Ii8xNzM1MDc5NTQvMzQxODk0MDQ1LTE1MzBlOGI1LWEwN2ItNDcyNS1hZmU3LTg3YTNhMTQ3NTZhZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQxNDM3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGRjOTQyYzhlZDU2MWExNTA4MGMxMTQ2NDY2NjdhYWEzZDU5MDU1MjNjNDlhMmViNmYxNzQ3YWVjMjBlMWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mTP4MCDASY33qk8uVH6PAMhS-7QG-MBpBogwn2cdZoo)

This worked for me,thank you very much

**Comment by samsesuj** [comment]
> **EDIT** OK I fixed my problem doing the following:
> 
> Opened up ComfyUI Manager
> 
> Clicked 'Install Models'
> 
> Searched for 'ipadapter' and installed 'ip-adapter-plus_sd15.safetensors' (I had already installed all the others on the list)
> 
> ![image](https://private-user-images.githubusercontent.com/39455501/340121447-d2c0793a-d7b2-48c5-8426-7be933d9bbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4Nzg1MjgsIm5iZiI6MTczNDg3ODIyOCwicGF0aCI6Ii8zOTQ1NTUwMS8zNDAxMjE0NDctZDJjMDc5M2EtZDdiMi00OGM1LTg0MjYtN2JlOTMzZDliYmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE0MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTQ1MWFhMzFmMDc0ZmQ0NTgwOGNjMmY3NDA0ZDZjYjdmYmEyYWNiYmI3MGQ0NTVlYTBiNDIxNWE2YmIwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.inF4dmgPwr2MQQEWVm4iyKplYJlfWoeh1lpg-6ONEpg)
> 
> And it's now working!
> 
> I've tried every single solution above, and I'm still getting the same error:
> 
> ```
> 
> Error occurred when executing IPAdapterUnifiedLoader:
> 
> IPAdapter model not found.
> 
>   File "C:\Users\Trism\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main\IPAdapterPlus.py", line 515, in load_models
>     raise Exception("IPAdapter model not found.")
> ```

This worked form me, thank you very much!!

**Comment by huibai117** [comment]
> 

> **编辑**好的，我通过以下方式解决了我的问题：
> 
> 打开 ComfyUI Manager
> 
> 点击“安装模型”
> 
> 搜索“ipadapter”并安装“ip-adapter-plus_sd15.safetensors”（我已经安装了列表中的所有其他产品）
> 
> ![图像](https://private-user-images.githubusercontent.com/39455501/340121447-d2c0793a-d7b2-48c5-8426-7be933d9bbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODM5NTMsIm5iZiI6MTczNTE4MzY1MywicGF0aCI6Ii8zOTQ1NTUwMS8zNDAxMjE0NDctZDJjMDc5M2EtZDdiMi00OGM1LTg0MjYtN2JlOTMzZDliYmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDAzMjczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NjBiNzhhZDFmNWM4MTZiOWU4ZTU4M2YyYTc4Nzc0YjdhNzhiMTEyMDg4NWUzOTI5ZGIwOTFlYjc0OGU0ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Atg9n7iUYNa9e3DBNNwAfb4ucWEZDcFpg4VNn5emzzE)
> 
> 现在它已经可以工作了！
> 
> 我已经尝试了上述每一个解决方案，但仍然收到相同的错误：
> 
> ```
> 
> Error occurred when executing IPAdapterUnifiedLoader:
> 
> IPAdapter model not found.
> 
>   File "C:\Users\Trism\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Trism\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main\IPAdapterPlus.py", line 515, in load_models
>     raise Exception("IPAdapter model not found.")
> ```

终于可以了 太感谢了！

**Comment by Laizin3721** [comment]
> ipadapter

worked for me,thank you very much!

**Comment by Laizin3721** [comment]
> I ran into this issue as well, seems for some reason the ipadapter path had not been added to folder_paths.py in the ComfyUI root directory. I added: `folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)`
> 
> and that seems to have solved the issue.

Worked for me,thank you very much!

**Comment by Upasunda** [comment]
@camiloteram did you check that it, for sure, is not in %APPDATA%\Local\Programs\comfyui-electron\ComfyUI ?

I have no idea how these pre-packaged distributions are organized, but it seems, according to https://github.com/Comfy-Org/desktop that the source is supposed to be placed there (and folder_paths.py is still very much part of the source of ComfyUI)

**Comment by alen-smajic** [comment]
I just stumbled upon this post while trying to find out why does ComfyUI not react to ipadapter path settings in the extra_model_paths.yaml file. I'm surprised this issue  has been known for so long and there is still no proper fix, which breaks whole production pipelines running on Comfy. 

Since I am starting ComfyUI from a Docker container and my weights are hosted on a separate network disk outside of ComyUI I heavily rely on the extra_model_paths.yaml. In case of the IpAdapter weights the only thing that worked was to create a symbolic link directly in the docker container to my ipadapter weights directory:

` 
RUN mkdir -p /runpod-volume/models/ipadapter && mkdir -p /comfyui/models && ln -s /runpod-volume/models/ipadapter /comfyui/models/ipadapter
`

This worked for me, hope it helps someone in the future, while the issue is not fixed in ComfyUI

**Comment by shitty34** [comment]
The only solution for me was:
Right-click on the node and click on "Fix node v2"
Hope that helps!

**Comment by slusht** [comment]
If anyone else is still in the dark, I struggled with this issue myself. After trying everything mentioned above to no avail, I figured out a solution and it's to edit the node's .py to target your model path folder. For my case, I replaced the class IPAdapterModelLoader with this code. Other Loaders could also be tweaked to target your paths. 

Open IPAdapterPlus.py in an editor, add this to the top with your model path:


```
import os
# other existing imports...

# Set your model path here
CUSTOM_IPADAPTER_PATH = r"YOUR PATH"
```

And replace class IPAdapterModelLoader: with:

```
class IPAdapterModelLoader:
    @classmethod
    def INPUT_TYPES(s):
        # List all .bin and .safetensors files in your IPAdapter folder
        if os.path.exists(CUSTOM_IPADAPTER_PATH):
            ipadapter_files = [
                f for f in os.listdir(CUSTOM_IPADAPTER_PATH)
                if f.endswith(".bin") or f.endswith(".safetensors")
            ]
        else:
            ipadapter_files = []

        return {"required": {"ipadapter_file": (ipadapter_files,)}}

    RETURN_TYPES = ("IPADAPTER",)
    FUNCTION = "load_ipadapter_model"
    CATEGORY = "ipadapter/loaders"

    def load_ipadapter_model(self, ipadapter_file):
        # Build full path and load the model
        full_path = os.path.join(CUSTOM_IPADAPTER_PATH, ipadapter_file)
        return (ipadapter_model_loader(full_path),)
```
