### ISSUE TITLE
CrossAttentionPatch.set_new_condition() got an unexpected keyword argument 'embeds_scaling'

### ISSUE THREAD

**Issue by Lalimec** [cubiq/ComfyUI_IPAdapter_plus#330]
So, i ve updated all my extensions and turns out IPAdapted Plus got a big one. I couldnt find any issues related to this. Problem is in an existing wf, i know there is a warning stating that it wont work with the old wf's but i would like to learn the reason at least. Or if it is possible to change only specific nodes to fix it?

```
Error occurred when executing IPAdapter:

CrossAttentionPatch.set_new_condition() got an unexpected keyword argument 'embeds_scaling'

File "/home/ubuntu/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/ubuntu/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/ubuntu/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 512, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args), )
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 325, in ipadapter_execute
set_model_patch_replace(model, patch_kwargs, ("input", id, index))
File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 144, in set_model_patch_replace
to["patches_replace"]["attn2"][key].set_new_condition(**patch_kwargs)
```

**Comment by haoqiangyu** [comment]
Maybe you are using it together with InstantID. The two are currently incompatible and you need to modify the InstantID code.
comfyui/custom_nodes/ComfyUI_InstantID/InstantID.py line:72
```
    def set_new_condition(self, weight, ipadapter, number, cond, uncond, weight_type="original", mask=None, sigma_start=0.0, sigma_end=1.0, unfold_batch=False):
```
to 
``` 
    def set_new_condition(self, weight, ipadapter, number, cond, uncond, weight_type="original", mask=None, sigma_start=0.0, sigma_end=1.0, unfold_batch=False, **kwargs):
```

**Comment by cubiq** [comment]
fixed

**Comment by Lalimec** [comment]
thanks, indeed i was using instantid. thought it would work, since there was no issue before the update.

**Comment by mockinbirdy** [comment]
Still doesn't work? Same error. ComfyUI, IPadapter and InstandID all updated.

**Comment by mockinbirdy** [comment]
Also, the IPadapter Advanced node in your Youtube vid is diff from the version you get after an update. In reality, there is no option 'no scaling'. Care to explain?

**Comment by Lalimec** [comment]
Mine is working now, did youchange the nodes and such?

**Comment by mockinbirdy** [comment]
As I said in my comment, I did update everything and use the IPadapter Advanced node now, which still throws this error.
