### ISSUE TITLE
'ClipVisionModel' object has no attribute 'processor'

### ISSUE THREAD

**Issue by MoonMoon82** [cubiq/ComfyUI_IPAdapter_plus#49]
After the latest update of ComfyUI I get this error message while running the "Load IPAdapter" node:

```
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 331, in apply_ipadapter
    clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 103, in zeroed_hidden_states
    inputs = clip_vision.processor(images=img, return_tensors="pt")
AttributeError: 'ClipVisionModel' object has no attribute 'processor'

Prompt executed in 1.42 seconds
```

Could you please check?

**Comment by cubiq** [comment]
this has been fixed already. please update IPAdapter

**Comment by MoonMoon82** [comment]
@cubiq I'm sorry I thought I already updated to the latest version. Thanks for your reply!

**Comment by Grewlz** [comment]
> this has been fixed already. please update IPAdapter #48

I updated to the latest version via ComfyUI Manager, and following your youtube video https://www.youtube.com/watch?v=7m9ZZFU3HWo&ab_channel=LatentVision

I still have the issue. 
![Screenshot 2024-04-03 182116](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/161898622/e35082a3-b9e1-49f8-bdb2-7b3cb1092869)


What am I doing wrong?
